apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80         # Service port inside cluster
      targetPort: 80   # Pod's containerPort
      nodePort: 30081  # External port (what we access from browser)