apiVersion: v1
kind: Service
metadata:
  name: k8django-service
spec:
  type: NodePort
  selector:
    app: k8django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # Optional: Expose at http://localhost:30080
